import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  { Head } from 'next/document';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Last Night Playerzz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
          <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </Head>
    
      <body className={inter.className}>{children}</body>
    </html>
  );
}
